### ISSUE TITLE
homebrew recipe for squashfuse?

### ISSUE THREAD

**Issue by rkrug** [vasi/squashfuse#8]
Hi Dave

I really like squashfuse and I use it on a Mac, It compiles without problems.

One question: are you planning to make a homebrew recipe for squashfuse as this would make installation and usage even easier?

Thanks,

Rainer

**Comment by vasi** [comment]
Hey, that's a great idea, but I don't really have time for this right now. I welcome anybody else who wants to do it though--usually it's not the author who becomes the package maintainer :)

If you do this, please do make sure it's clear that this is NOT the same software as squashfs on linux, it just has similar functionality. I don't want anyone to email the squashfs authors because of a bug in my code.

**Comment by chipturner** [comment]
homebrew has a requirement for a repository to be "notable" enough before it can be added to homebrew itself.  It's possible to create custom taps but until this repo is more used/starred/forked, it can't be in the main one.  Closing this out for now but I'll comment if I or someone else does make a custom tap someday.
